# Generated by Django 3.1.13 on 2022-02-23 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_gift_gst_slab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='combo_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gift_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='payment',
        ),
        migrations.AddField(
            model_name='combo_product',
            name='pruduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.product'),
        ),
        migrations.AddField(
            model_name='gift',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shopping_order'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipping',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.product'),
        ),
        migrations.AddField(
            model_name='transaction_report',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction_report',
            name='payment_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.payment'),
        ),
        migrations.AddField(
            model_name='transaction_report',
            name='shopping_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shopping_order'),
        ),
        migrations.AlterField(
            model_name='transaction_report',
            name='shipping_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shipping'),
        ),
        migrations.DeleteModel(
            name='Product_discription',
        ),
    ]
