# Generated by Django 3.1.13 on 2022-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220223_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo_product',
            name='pruduct',
        ),
        migrations.AddField(
            model_name='combo_product',
            name='pruduct',
            field=models.ManyToManyField(blank=True, null=True, to='customer.Product'),
        ),
    ]
