# Generated by Django 3.1.13 on 2022-02-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220223_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='combo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.combo_product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='gift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.gift'),
        ),
        migrations.AddField(
            model_name='cart',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.offer'),
        ),
    ]
