# Generated by Django 3.1.13 on 2022-02-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220223_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='product',
        ),
        migrations.AddField(
            model_name='gift',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='customer.Product'),
        ),
    ]
