# Generated by Django 3.1.13 on 2022-02-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220223_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='color',
        ),
        migrations.AddField(
            model_name='gift',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, related_name='gift_color', to='customer.Product_colors'),
        ),
    ]
