# Generated by Django 3.1.13 on 2022-02-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220223_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, to='customer.Product'),
        ),
    ]
