# Generated by Django 3.1.13 on 2022-02-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220223_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='combo_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.combo_product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='gift_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.gift'),
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='product_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.product'),
        ),
    ]
