# Generated by Django 3.1.13 on 2022-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20220223_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
