# Generated by Django 3.1.13 on 2022-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_payment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, choices=[('$', '$'), ('Rs', 'Rs')], max_length=100, null=True),
        ),
    ]
