# Generated by Django 3.1.13 on 2022-02-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_payment_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='product_id',
        ),
        migrations.AddField(
            model_name='shipping',
            name='order_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.shopping_order'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='gst_slab',
            field=models.CharField(choices=[('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%')], default='5%', max_length=100),
        ),
    ]
