# Generated by Django 3.1.13 on 2022-02-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220223_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipping_type',
            field=models.CharField(blank=True, choices=[('a', 'same day delivery'), ('b', 'two day delivery'), ('c', 'overnight shipping')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
