# Generated by Django 3.1.13 on 2022-02-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20220223_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo_product',
            name='upcell_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='upcell', to='customer.Product'),
        ),
        migrations.AlterField(
            model_name='combo_product',
            name='pruduct',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='customer.Product'),
        ),
    ]
