# Generated by Django 3.1.13 on 2022-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=15)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(unique=True)),
                ('country_code', models.IntegerField()),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='customer/profile')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('aadhar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('India', 'US'), ('India', 'Auatralia'), ('India', 'Singapure')], max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo')),
                ('gstin_no', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
